site_name: Robert Birek
site_author: Robert Birek
site_description: "Portfolio Robert Birek — projekty IT, automatyzacja, AI, e-commerce i administracja systemami."

repo_name: RobertBirek/aboutme
repo_url: https://github.com/RobertBirek/aboutme
edit_uri: "edit/main/docs/"

theme:
  name: material
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: blue grey
    accent: amber
  font:
    text: "Roboto"
    code: "Fira Code"
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.tabs.link
    - content.code.copy
    - content.action.edit
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - toc:
      permalink: true
  
copyright: "© 2025 Robert Birek. Wszelkie prawa zastrzeżone."
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RobertBirek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/robertbirek/
    - icon: fontawesome/solid/envelope
      link: mailto:robert@birek.online
    - icon: fontawesome/solid/phone
      link: tel:+48783924008

nav:
  - O mnie: index.md
  - Moje Projekty:
    - Obecne:
      - www.taxbell.pl: projects/wwwtaxbell/index.md
      - www.taxlonga.pl: projects/wwwtaxlonga/index.md
      - Song2Me: projects/song2me/index.md
    - Archiwalne:
      - Iris: projects/iris/index.md
      - Run4You: projects/run4you/index.md
  - Kontakt: kontakt.md
