site_name: Robert Birek
site_author: Robert Birek
site_description: Portfolio Robert Birek

repo_name: RobertBirek/aboutme
repo_url: https://github.com/RobertBirek/aboutme

theme:
  name: material
  favicon: assets/favicon.ico
  palette:
    primary: blue grey
    accent: amber
markdown_extensions:
  - attr_list
  
copyright: © 2025 Robert Birek
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:robert.birek@op.pl

nav:
- O mnie: index.md
- Moje Projekty:
  - Obecne:
    - "www.taxbell.pl": projects/wwwtaxbell/index.md
    - "www.taxlonga.pl": projects/wwwtaxlonga/index.md
    - "Song2Me": projects/song2me/index.md
  - Poprzednie:
    - "Iris": projects/iris/index.md
    - "Run4oyu": projects/run4you/index.md
